import { X } from 'lucide-react'

export function Cheatsheet({ onClose }: { onClose: () => void }) {
  return <div className="cheatsheet-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><dialog open className="cheatsheet-dialog" aria-modal="true" aria-labelledby="cheatsheet-title">
    <div className="cheatsheet-heading"><div><span>Reference</span><h2 id="cheatsheet-title">Markdown cheat sheet</h2></div><button className="icon-button" onClick={onClose} aria-label="Close cheat sheet"><X size={18} /></button></div>
    <div className="cheatsheet-grid"><section><h3>Markdown</h3><dl>
      <div><dt><code># Title</code></dt><dd>Document chapter</dd></div><div><dt><code>## Section</code></dt><dd>Section heading</dd></div><div><dt><code>**bold**</code></dt><dd>Bold text</dd></div><div><dt><code>_italic_</code></dt><dd>Italic text</dd></div><div><dt><code>- Item</code></dt><dd>Bulleted list</dd></div><div><dt><code>1. Item</code></dt><dd>Numbered list</dd></div><div><dt><code>&gt; Quote</code></dt><dd>Block quote</dd></div><div><dt><code>[text](url)</code></dt><dd>Link</dd></div><div><dt><code>[1][2]</code></dt><dd>Adjacent numeric citations</dd></div><div><dt><code>doi:10.xxxx/xxxx</code></dt><dd>Resolvable DOI in References</dd></div><div><dt><code>PMID: 12345678</code></dt><dd>Resolvable PubMed citation</dd></div><div><dt><code>![alt](url)</code></dt><dd>Proportional inline image preview</dd></div><div><dt><code>![alt](url)&#123;size=40%&#125;</code></dt><dd>Figure size as a share of the scene</dd></div><div><dt><code>caption text on the next line</code></dt><dd>Same-paragraph text under an image becomes its legend</dd></div><div><dt><code>```ts &#123;2-3|5|all&#125;</code></dt><dd>Progressive code line highlighting</dd></div><div><dt><code>&#123;lines:true,startLine:5&#125;</code></dt><dd>Code line numbers and starting line</dd></div><div><dt><code>```mermaid</code></dt><dd>Responsive Mermaid diagram</dd></div><div><dt><code>::code-group</code></dt><dd>Tabbed code alternatives</dd></div><div><dt><code>$$ x $$</code></dt><dd>Display math</dd></div>
    </dl></section><section><h3>Presentation hints</h3><dl>
      <div><dt><code>&lt;!-- present: break --&gt;</code></dt><dd>Force a scene break</dd></div><div><dt><code>&lt;!-- present: keep --&gt;</code></dt><dd>Keep the next block together</dd></div><div><dt><code>&lt;!-- present: hero --&gt;</code></dt><dd>Make the next image a full-height figure</dd></div><div><dt><code>&lt;!-- present: hide --&gt;</code></dt><dd>Hide the next block in presentation</dd></div><div><dt><code>&lt;!-- present: only --&gt;</code></dt><dd>Show the next block only in presentation</dd></div><div><dt><code>&lt;!-- present: step --&gt;</code></dt><dd>Reveal the next list item by item</dd></div><div><dt><code>&lt;!-- present: group --&gt;</code></dt><dd>Keep blocks until <code>end-group</code> on one scene</dd></div><div><dt><code>&lt;!-- present: columns --&gt;</code></dt><dd>Start responsive columns; each H3 starts a column</dd></div><div><dt><code>&lt;!-- present: column --&gt;</code></dt><dd>Start another column without a subtitle</dd></div><div><dt><code>&lt;!-- present: end-columns --&gt;</code></dt><dd>End the column group</dd></div><div><dt><code>&lt;!-- speaker note --&gt;</code></dt><dd>Marp-compatible note for the current scene</dd></div><div><dt><code>[click]</code></dt><dd>Advance presenter-note emphasis with reveals</dd></div><div><dt><code>+ / − / 0</code></dt><dd>Zoom presentation content</dd></div>
    </dl><p>Hints apply to the block immediately following the comment. Type <code>&lt;!-- present:</code> in the editor to autocomplete one.</p></section></div>
  </dialog></div>
}
